// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/helpers/fetchRecur/__tests__/fetchRecur.fixtures.ts";
import * as $1 from "./routes/helpers/fetchRecur/__tests__/fetchRecur.test.ts";
import * as $2 from "./routes/helpers/fetchRecur/fetchRecur.ts";
import * as $3 from "./routes/helpers/fetchRecur/index.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/types/index.ts";
import * as $$0 from "./islands/Countdown.tsx";

const manifest = {
  routes: {
    "./routes/helpers/fetchRecur/__tests__/fetchRecur.fixtures.ts": $0,
    "./routes/helpers/fetchRecur/__tests__/fetchRecur.test.ts": $1,
    "./routes/helpers/fetchRecur/fetchRecur.ts": $2,
    "./routes/helpers/fetchRecur/index.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/types/index.ts": $5,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
